/* Autogenerated with kurento-module-creator */

#ifndef __CUSTOM_MIXER_IMPL_HPP__
#define __CUSTOM_MIXER_IMPL_HPP__

#include "HubImpl.hpp"
#include "CustomMixer.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace mymodule
{
class CustomMixerImpl;
} /* mymodule */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::mymodule::CustomMixerImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace mymodule
{

class CustomMixerImpl : public HubImpl, public virtual CustomMixer
{

public:

  CustomMixerImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~CustomMixerImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* mymodule */
} /* module */
} /* kurento */

#endif /*  __CUSTOM_MIXER_IMPL_HPP__ */
